import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NextAuthProvider from "@/provider/nextAuthProvider";
import Navbar from "@/components/Navbar/navbar";
import { useSession } from "next-auth/react";
// import LoadingForUser from "@/components/loadingforUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PlaceForm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider> <Navbar/> {children}</NextAuthProvider>
      </body>
    </html>
  );
}
