import type { Metadata } from "next";
import "@/app/globals.css";
import FormTable from "@/components/formTable/formTable";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../api/auth/[...nextauth]/options";
import { igetUSER } from "@/types/getUSER";
import connect from "@/db/mongo.config";
import USER from "@/models/user";
import FORM from "@/models/form";



export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

type iFormData = {
  _id: string;
  title?: string;
  date?: string;
  time?: string;
  expiry?: string;
  expiry_time?: string;
  state?: string;
  attempt?: string;
  key?: string;
  fields?: any[];
  __v?: number;
}[]

export default async function Form() {
  const {user} = await getServerSession(authOptions) as igetUSER
  if (!user){
    return(<><h1>Please Login</h1></>  )
  }
  console.log(user.email)
  connect();
  const UserDataOnDB= await USER.findOne({email:user.email})
  console.log(UserDataOnDB.forms);
  const forms = await FORM.find({_id:{$in:UserDataOnDB.forms}}) as iFormData
  console.log(forms);
  return (
    <>
      <FormTable formData={forms}/>
    </>
  );
}
