name: Build and Deploy the application to EC2

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check Out Repo
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/placeform:latest

      # Verify the pushed image
      - name: Verify Pushed Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/placeform:latest

      # Deploy the Docker image to an EC2 instance
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull the latest application image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/placeform:latest
            
            # Stop and remove existing containers
            sudo docker stop placeform-app || true
            sudo docker rm placeform-app || true

            # Run application container
            sudo docker run -d --name placeform-app -p 3000:3000 -e "NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}}" -e "JWT_Secret=${{secrets.JWT_Secret}}" -e "WEBSITE_URL=${{secrets.WEBSITE_URL}}" -e "NEXT_PUBLIC_WEBSITE_URL=${{secrets.NEXT_PUBLIC_WEBSITE_URL}}" -e "GOOGLE_GENERATIVE_TOKEN= ${{secrets.GOOGLE_GENERATIVE_TOKEN}}" -e "NEXTAUTH_SECRET= ${{secrets.NEXTAUTH_SECRET}}" -e "MONGO_URL=${{secrets.MONGO_URL}}" ${{ secrets.DOCKER_USERNAME }}/placeform:latest